config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :subs, except: [:destroy]

  resources :users
  resource :session

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :post, :content, presence: true

  belongs_to :author, foreign_key: :user_id, class_name: :User
  belongs_to :post
  has_many :child_comments, foreign_key: :parent_comment_id, class_name: :Comment
  has_many :votes, as: :votable

  attr_reader :score

  def score
    @score = 0
    self.votes.each {|vote| @score += vote.value.to_i}
    @score
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :author, :post_subs, :title, presence: true

  belongs_to :author, foreign_key: :user_id, class_name: :User
  has_many :post_subs
  has_many :subs, through: :post_subs
  has_many :comments
  has_many :votes, as: :votable

  attr_reader :score

  def comments_by_parent_id
    children = Hash.new { |h, k| h[k] = [] }
    self.comments.each do |comment|
      children[comment.parent_comment_id] << comment
    end
    children

  end

  def score
    @score = 0
    self.votes.each {|vote| @score += vote.value.to_i}
    @score
  end
end

app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post, :sub, presence: true

  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :moderator, :title, :description, presence: true

  belongs_to :moderator, foreign_key: :user_id, class_name: :User
  has_many :post_subs
  has_many :posts, through: :post_subs
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, :password_digest, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  before_validation :ensure_session_token

  has_many :subs, foreign_key: :user_id, class_name: :Sub, inverse_of: :moderator
  has_many :posts, inverse_of: :author
  has_many :comments, inverse_of: :author
  

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)

  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :value, presence: true, inclusion: ["-1", "+1"]

  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def require_login
    redirect_to new_session_url unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_post_comment
    end
  end

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
    @comments_by_parent_id = @comment.post.comments_by_parent_id
  end

  def upvote
    @comment = Comment.find(params[:id])
    @comment.votes << Vote.create(value: "+1")
    redirect_to :back
  end

  def downvote
    @comment = Comment.find(params[:id])
    @comment.votes << Vote.create(value: "-1")
    redirect_to :back

  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_author, only: [:update, :edit]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to new_post_url
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def ensure_author
    unless current_user.posts.where(id: params[:id]).exists?
      redirect_to post_url(Post.find(params[:id]))
      flash[:errors] = ["Only an author can edit a post"]
    end
  end

  def update
    post = Post.find(params[:id])
    if post.update_attributes(post_params)
      redirect_to post_url(post)
    else
      flash[:errors] = post.errors.full_messages
      redirect_to post_url(post)
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments_by_parent_id = @post.comments_by_parent_id
  end

  def destroy
  end

  def upvote
    @post = Post.find(params[:id])
    @post.votes << Vote.create(value: "+1")
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    @post.votes << Vote.create(value: "-1")
    redirect_to :back
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      login(user)
      redirect_to user_url(user)
    else
      flash[:errors] = ["invalid credentials"]
      redirect_to new_session_url
    end
  end

  def destroy
    logout
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_moderator, only: [:edit, :update]

  def index
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      redirect_to subs_url
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def ensure_moderator
    unless current_user.subs.where(id: params[:id]).exists?
      redirect_to sub_url(Sub.find(params[:id]))
      flash[:errors] = ["Only a moderator can edit a sub"]
    end
  end

  def update
    sub = Sub.find(params[:id])
    if sub.update_attributes(sub_params)
      redirect_to sub_url(sub)
    else
      flash[:errors] = sub.errors.full_messages
      redirect_to sub_url(sub)
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])
  end


private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type=hidden name=authenticity_token value=#{h(form_authenticity_token)}>".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_comment.html.erb
<h3><%= link_to comment.content, comment_url(comment) %></h3>
<p>Created By: <%= comment.author.username %><br><%= comment.created_at %></p>
<%= comment.score %>
<%= button_to 'Upvote', upvote_comment_url(comment), method: :post %>
<%= button_to 'Downvote', downvote_comment_url(comment), method: :post %>

<br>

<% sorted_comments = @comments_by_parent_id[comment.id].sort_by{ |com| com.score}.reverse %>

<ul>
  <% sorted_comments.each do |child| %>
      <li>
        <%= render 'comment', comment: child %>
      </li>
  <% end %>
</ul>

app/views/application/_comment_form.html.erb
<form action="<%=action_url%>" method="post">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>


  <label>Comment
    <br>
    <textarea name="comment[content]" rows="8" cols="80"><%= comment.content %></textarea>
  </label>
    <br>


  <input type="hidden" name="comment[post_id]" value= <%= post_id %> >

  <input type="hidden" name="comment[parent_comment_id]" value= <%= parent_id %> >

  <input type="submit" value= <%= action_url == comments_url ? 'Create Comment' : 'Update Comment' %> >
</form>

app/views/application/_login_form.html.erb
<form action= "<%= action_url %>" method="post">
  <%= auth_token %>

  <label>Username
  <input type="text" name="user[username]" value="">
  </label>


  <label>Password
  <input type="password" name="user[password]" value="">
  </label>

  <input type="submit">
</form>

app/views/application/_post_form.html.erb
<form action="<%=action_url%>" method="post">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>


  <label>Title
    <input type="text" name="post[title]" value="<%= post.title %>" >
  </label>
  <br>
  <label>URL
    <input name="post[url]" value="<%= post.url %>">
  </label>
  <br>

  <label>Content
    <br>
    <textarea name="post[content]" rows="8" cols="80"><%= post.content %></textarea>
  </label>
    <br>

  <input type="hidden" name="post[sub_ids][]" value="">

  <label>Subs
    <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
             name="post[sub_ids][]"
             value= <%= sub.id %>
             <%= "checked" if post.sub_ids.include?(sub.id) %>>
    </label>
    <% end %>
  </label>
  <br>
  <input type="submit" value= <%= action_url == posts_url ? 'Create Post' : 'Update Post' %> >
</form>

app/views/application/_sub_form.html.erb
<form action="<%=action_url%>" method="post">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>


  <label>Title
    <input type="text" name="sub[title]" value="<%= sub.title %>" >
  </label>
  <br>
  <label>Description
    <br>
    <textarea name="sub[description]" rows="8" cols="80"><%= sub.description %></textarea>
  </label>
  <br>

  <input type="submit" value= <%= action_url == subs_url ? 'Create Sub' : 'Update Sub' %> >
</form>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'comment_form', action_url: comments_url,
                           action: :new,
                           comment: @comment,
                           post_id: params[:post_id],
                           parent_id: nil%>

app/views/comments/show.html.erb
<h2><%= @comment.content %></h2>
<h3><%=link_to @comment.post.title, post_url(@comment.post) %></h3>
<br>

<label>Comments
  <%= render 'comment', comment: @comment %>
</label>

<%= render 'comment_form', action_url: comments_url,
                           action: :new,
                           comment: Comment.new,
                           parent_id: @comment.id,
                           post_id: @comment.post.id%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

<% if current_user %>
  <p><%= current_user.username %> currently logged in</p>
  <%= button_to 'Log Out', session_url, method: :delete %>
<% else %>
  <%= button_to 'Log In', new_session_url, method: :get %>
<% end %>

  <%= link_to 'All Subs', subs_url %>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'post_form', action_url: post_url(@post), action: :edit, post: @post %>

app/views/posts/new.html.erb
<h1>New Post</h1>


<%= render 'post_form', action_url: posts_url, action: :new, post: @post %>

app/views/posts/show.html.erb
<h1>Title: <%= @post.title %></h1>
<h3>URL: <%= @post.url %></h3>
<h2><%= @post.content %></h2>


<h3>Subs</h3>
<ul>
  <% @post.subs.each do |sub| %>
  <li><%= link_to sub.title, sub_url(sub) %></li>
  <% end %>
</ul>

<br>

<% @all_comments = @post.comments.includes(:author) %>

<% @all_comments = @all_comments.sort_by{|com| com.score}.reverse %>

<h3>Comments</h3>
<ul>
  <% @all_comments.each do |comment| %>
    <% if comment.parent_comment_id == nil %>
      <li>
        <%= render 'comment', comment: comment,
                              child_comments: @post.comments_by_parent_id[comment.id] %>
      </li>
    <% end %>
  <br>
  <% end %>
</ul>

<br>



<%= link_to 'New Comment', new_post_comment_url(@post) %>
<%= button_to 'Edit Post', edit_post_url, method: :get %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render 'sub_form', action_url: sub_url(@sub), sub: @sub, action: :edit %>

app/views/subs/index.html.erb
<h1>Subs</h1>


<ul>

  <% Sub.all.each do |sub| %>
    <li>
    <%= link_to sub.title, sub_url(sub) %>
    <br>
    </li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create a Sub</h1>

<%= render 'sub_form', action_url: subs_url, sub: @sub, action: :new %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>

<%= button_to 'Edit Sub', edit_sub_url, method: :get %>

<%= button_to 'Create Post', new_post_url(@sub), method: :get %>

<br>

<% sorted_posts = @sub.posts.sort_by{|p| p.score}.reverse %>

<h2>Posts</h2>
<ul>
<% sorted_posts.each do |post| %>
  <li>
  <%= link_to post.title, post_url(post) %>
  <%= post.score %>
  <%= button_to 'Upvote', upvote_post_url(post), method: :post %>
  <%= button_to 'Downvote', downvote_post_url(post), method: :post %>
  <br>
  </li>
<% end %>
</ul>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'login_form', action_url: users_url %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>


<h3>Subs</h3>
<ul>
  <% @user.subs.each do |sub| %>
  <li><%= link_to sub.title, sub_url(sub) %></li>
  <% end %>
</ul>




<%= link_to "Create New Sub", new_sub_url, method: :get %>